services:
  odineye:
    container_name: "odineye"
    build:
      context: .
      dockerfile: ./OdinEye/Dockerfile
    restart: unless-stopped
    pull_policy: always
    volumes:
      - odineye-data:/odineye
    ports:
      - 8080:8080
    environment:
      TZ: "America/Phoenix"
      ODINEYE_PATH: "/odineye"

volumes:
  odineye-data:  