services:
  lumisky:
    container_name: "lumisky"
    build:
      context: .
      dockerfile: ./LumiSky/Dockerfile
    restart: unless-stopped
    volumes:
      - lumisky-data:/lumisky
    network_mode: host
    ports:
      - 8080:8080
    environment:
      TZ: "America/Phoenix"
      LUMISKY_PATH: "/lumisky"

  indiserver:
    container_name: "indiserver"
    image: ghcr.io/twinkle-astronomy/indi_server:v2.0.9-1
    restart: unless-stopped
    pull_policy: always
    privileged: true
    volumes:
      - indi_server-config:/root/.indi
    network_mode: host
    ports:
      - 7624:7624
    command: [
      "indiserver",
      "-v",
      "-m", "1024",
      "-r", "0",
      "-d", "1024",
      # Add your indi devices here
      "indi_simulator_ccd",
      #"indi_asi_ccd",
      #"indi_asi_wheel",
      #"indi_asi_focuser",
      #"indi_eqmod_telescope",
    ]

volumes:
  lumisky-data:
  indi_server-config: