services:
  odineye:
    container_name: "odineye"
    image: ghcr.io/alexhelms/odineye:latest
    restart: unless-stopped
    pull_policy: always
    user: 1654:1654
    volumes:
      - odineye-data:/odineye
    network_mode: host
    ports:
      - 8080:8080
    environment:
      TZ: "America/Phoenix"
      ODINEYE_PATH: "/odineye"

  indiserver:
    container_name: "indiserver"
    image: ghcr.io/twinkle-astronomy/indi_server:v2.0.9-1
    restart: unless-stopped
    pull_policy: always
    privileged: true
    volumes:
      - indi_server-config:/root/.indi
    network_mode: host
    ports:
      - 7624:7624
    command: [
      "indiserver",
      "-v",
      "-m", "1024",
      "-r", "0",
      "-d", "1024",
      # Add your indi devices here
      "indi_simulator_ccd",
      #"indi_asi_ccd",
      #"indi_asi_wheel",
      #"indi_asi_focuser",
      #"indi_eqmod_telescope",
    ]

volumes:
  odineye-data:
  indi_server-config: