services:
  lumisky:
    container_name: "lumisky"
    image: ghcr.io/alexhelms/lumisky:latest
    restart: unless-stopped
    user: 1654:1654
    volumes:
      - ~/lumisky:/lumisky
    ports:
      - 8080:8080
    environment:
      TZ: "America/Phoenix"
      LUMISKY_PATH: "/lumisky"

  indiserver:
    container_name: "indiserver"
    image: ghcr.io/twinkle-astronomy/indi_server:v2.1.1-202412060709
    restart: unless-stopped
    privileged: true
    volumes:
      - ~/.indi:/root/.indi
    network_mode: host
    ports:
      - 7624:7624
    command: [
      "indiserver",
      "-v",
      "-m", "1024",
      "-r", "0",
      "-d", "1024",
      "indi_asi_ccd"
    ]
